name: Update SST Data

on:
  workflow_dispatch: # This lets you trigger it manually for testing
  schedule:
    - cron: '0 */4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install numpy requests netCDF4

      - name: Run Script
        run: |
          echo "VERIFYING LINE 14:"
          sed -n '14p' update_sst.py
          python update_sst.py

      - name: Commit and Push
        run: |
          git config --global user.name "SST-Bot"
          git config --global user.email "bot@github.com"
          git add sst_data.json || echo "No changes"
          git commit -m "Update SST" || exit 0
          git push
