name: Update SST Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This gives the bot permission to save files to your repo
      
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install numpy requests netCDF4

      - name: Run Script
        run: python update_sst.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Force git to see the new folder
          git add historical_data/*.json
          git add sst_data.json || true
          
          # Commit only if there are changes. || exit 0 prevents the "Error" if nothing is new.
          git commit -m "Automated SST History Update" || exit 0
          git push
